name: CI
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.9'
        os:
          - macOS-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v3

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Show Julia version
        run: julia --version

      - name: Install dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests with coverage
        run: julia --project=. --code-coverage=all -e 'using Pkg; Pkg.test(coverage=true)'

      - name: Generate LCOV file
        run: julia --project=. -e 'using Coverage; LCOV.writefile("lcov.info", process_folder("coverage"))'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          slug: Aero-Spec/RoombaPOMDPs.jl
          files: lcov.info
