name: CI
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.6'
        os:
          - macOS-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v1

      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Install dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests with coverage
        run: julia --project=. --code-coverage=lcov -e 'using Pkg; Pkg.test()'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          slug: Aero-Spec/RoombaPOMDPs.jl
